# Generated by Django 4.2.5 on 2023-10-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_text',
            new_name='pub_date',
        ),
    ]
